name: Create a Release Pull Request

on:
  workflow_dispatch:
    inputs:
      semver-type:
        description: "Semantic version to be released"
        required: true
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    env:
      SEMVER_TYPE: ${{ github.event.inputs.semver-type }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install dev requirements
        run: make requirements

      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Calculate current and next version
        id: version
        run: |
          echo "CURRENT_VERSION=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
          echo "NEW_VERSION=$(bump-my-version show --increment $SEMVER_TYPE new_version)" >> $GITHUB_OUTPUT

      - name: Execute bump version
        run: bump-my-version bump $SEMVER_TYPE

      - name: Collect changelog entries
        run: make changelog-collect

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CURRENT_VERSION: ${{ steps.version.outputs.CURRENT_VERSION }}
          NEW_VERSION: ${{ steps.version.outputs.NEW_VERSION }}
        with:
          commit-message: "chore: bump version `v${{ env.CURRENT_VERSION }}` â†’ `v${{ env.NEW_VERSION }}`"
          title: "Release `v${{ env.NEW_VERSION }}`"
          body: |
            ### Description

            This PR bumps the version from `v${{ env.CURRENT_VERSION }}` to `v${{ env.NEW_VERSION }}`.

            The changelog has been automatically generated using `scriv`.
          branch: release-v${{ env.NEW_VERSION }}
