name: Create a new GitHub Release

on:
  workflow_dispatch:

jobs:
  create-github-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install dev requirements
        run: make requirements

      - name: Install pandoc for using scriv with RST
        run: sudo apt install -y pandoc

      - name: Configure Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Read current version
        id: version
        run: |
          echo "CURRENT_VERSION=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      - name: Create and push Git tag
        env:
          CURRENT_VERSION: ${{ steps.version.outputs.CURRENT_VERSION }}
        run: |
          git tag -a "v$CURRENT_VERSION" -m "Release v$CURRENT_VERSION"
          git push origin "v$CURRENT_VERSION"

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: scriv github-release --repo=openedx/openedx-filters
